### ISSUE TITLE
The problem with the installation of Plugin-Developers / openmediavault-mysql ver 2.1

### ISSUE THREAD

**Issue by aswest** [OpenMediaVault-Plugin-Developers/openmediavault-mysql#3]
I installed distribution ver. openmediavault 2.1 64-bit. After I put the Plugin-Developers / openmediavault-mysql ver 2.1. I took away: http://omv-extras.org/debian/pool/main/o/.
When you try to install the Plugin-Developers / openmediavault-mysql ver 2.1 error. Unresolved dependency.

~Apt-get install openmediavault-mysql
Reading package lists ... Done
Building dependency tree
Reading state information ... Done
Some packages can not be installed. Perhaps you are asking the impossible,
or using the unstable distribution that some required
packages have not yet been created or been moved out of Incoming.
The following information may help you:

The packages have unmet dependencies:
  openmediavault-mysql: Depends: mywebsql but it can not be installed
E: Unable to correct problems, you have delayed (held) broken packages

I tried to install these packages here.

~apt-get install mysql-server mysql-client  php5-mysql
Did not help.

~uname -m
x86_64

~ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.9 (wheezy)
Release:        7.9
Codename:       wheezy

**Comment by ghost** [comment]
You need to install mywebsql. You can use [this](https://github.com/OpenMediaVault-Plugin-Developers/mywebsql) repo to build the package.
