### ISSUE TITLE
scheduled backup option on a mariadb doesn't work

### ISSUE THREAD

**Issue by happyreacer** [OpenMediaVault-Plugin-Developers/openmediavault-mysql#5]
When the cron command is executed, it returns an error:
`Fehler #0:OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; export SHELL=/bin/sh; sudo --shell --non-interactive --user=root -- omv-rpc MySql dumpDatabaseToSharedFolder '{"uuid":"b064e8ae-f414-4f48-ba16-5fbaf33a0bfa"}' 2>&1' with exit code '1': {"response":null,"error":{"code":0,"message":"Failed to execute command 'export PATH=\/bin:\/sbin:\/usr\/bin:\/usr\/sbin:\/usr\/local\/bin:\/usr\/local\/sbin; export LANG=C; mysqldump --defaults-extra-file='\/etc\/openmediavault\/mysqldump.cnf' --all-databases --result-file=\/srv\/dev-disk-by-label-data2\/mysql\/mysql-2018-02-21T08:09:51+0100.sql' with exit code '2': ","trace":"OMV\\ExecException: Failed to execute command 'export PATH=\/bin:\/sbin:\/usr\/bin:\/usr\/sbin:\/usr\/local\/bin:\/usr\/local\/sbin; export LANG=C; mysqldump --defaults-extra-file='\/etc\/openmediavault\/mysqldump.cnf' --all-databases --result-file=\/srv\/dev-disk-by-label-data2\/mysql\/mysql-2018-02-21T08:09:51+0100.sql' with exit code '2': in \/usr\/share\/php\/openmediavault\/system\/process.inc:175\nStack trace:\n#0 \/usr\/share\/openmediavault\/engined\/rpc\/mysql.inc(277): OMV\\System\\Process->execute()\n#1 \/usr\/share\/openmediavault\/engined\/rpc\/mysql.inc(175): OMV\\Engined\\Rpc\\MySql->dumpDatabase('\/srv\/dev-disk-b...', '\/etc\/openmediav...')\n#2 [internal function]: OMV\\Engined\\Rpc\\MySql->dumpDatabaseToSharedFolder(Array, Array)\n#3 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(123): call_user_func_array(Array, Array)\n#4 \/usr\/share\/php\/openmediavault\/rpc\/rpc.inc(86): OMV\\Rpc\\ServiceAbstract->callMethod('dumpDatabaseToS...', Array, Array)\n#5 \/usr\/sbin\/omv-engined(536): OMV\\Rpc\\Rpc::call('MySql', 'dumpDatabaseToS...', Array, Array, 1)\n#6 {main}"}} in /usr/share/openmediavault/engined/rpc/cron.inc:175Stack trace:#0 /usr/share/php/openmediavault/rpc/serviceabstract.inc(528): OMVRpcServiceCron->{closure}('/tmp/bgstatusD6...', '/tmp/bgoutputUR...')#1 /usr/share/openmediavault/engined/rpc/cron.inc(179): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))#2 [internal function]: OMVRpcServiceCron->execute(Array, Array)#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('execute', Array, Array)#5 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('Cron', 'execute', Array, Array, 1)#6 {main} `

The output from `dpkg -l | grep -E "mysql|mariadb"`
```
ii  mariadb-client-10.1              10.1.26-0+deb9u1               amd64        MariaDB database client binaries  
ii  mariadb-client-core-10.1         10.1.26-0+deb9u1               amd64        MariaDB database core client binaries
ii  mariadb-common                   10.1.26-0+deb9u1               all          MariaDB common metapackage                     
ii  mariadb-server                   10.1.26-0+deb9u1               all          MariaDB database server (metapackage depending on the latest version)
ii  mariadb-server-10.1              10.1.26-0+deb9u1               amd64        MariaDB database server binaries                                
ii  mariadb-server-core-10.1         10.1.26-0+deb9u1               amd64        MariaDB database core server files                              
ii  mysql-common                     5.8+1.0.2                      all          MySQL database common files, e.g. /etc/mysql/my.cnf             
ii  openmediavault-mysql             4.1.1                          all          MySQL plugin for OpenMediaVault.                                                  
ii  php7.0-mysql                     7.0.27-0+deb9u1                amd64        MySQL module for PHP   
```

**Comment by happyreacer** [comment]
I have tried it again with version 4.1.2 and have the error:
`Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; export SHELL=/bin/sh; sudo --shell --non-interactive --user=root -- omv-rpc MySql dumpDatabaseToSharedFolder '{"uuid":"eb501737-cd21-4cb3-8fca-24a497e60cda"}' 2>&1' with exit code '1': {"response":null,"error":{"code":0,"message":"Failed to execute command 'export PATH=\/bin:\/sbin:\/usr\/bin:\/usr\/sbin:\/usr\/local\/bin:\/usr\/local\/sbin; export LANG=C; mysqldump --defaults-extra-file='\/etc\/openmediavault\/mysqldump.cnf' --all-databases --result-file=\/srv\/dev-disk-by-label-data3\/backup_mysql\/mysql-2018-05-14T09:37:31+0200.sql' with exit code '2': ","trace":"OMV\\ExecException: Failed to execute command 'export PATH=\/bin:\/sbin:\/usr\/bin:\/usr\/sbin:\/usr\/local\/bin:\/usr\/local\/sbin; export LANG=C; mysqldump --defaults-extra-file='\/etc\/openmediavault\/mysqldump.cnf' --all-databases --result-file=\/srv\/dev-disk-by-label-data3\/backup_mysql\/mysql-2018-05-14T09:37:31+0200.sql' with exit code '2': in \/usr\/share\/php\/openmediavault\/system\/process.inc:175\nStack trace:\n#0 \/usr\/share\/openmediavault\/engined\/rpc\/mysql.inc(277): OMV\\System\\Process->execute()\n#1 \/usr\/share\/openmediavault\/engined\/rpc\/mysql.inc(175): OMV\\Engined\\Rpc\\MySql->dumpDatabase('\/srv\/dev-disk-b...', '\/etc\/openmediav...')\n#2 [internal function]: OMV\\Engined\\Rpc\\MySql->dumpDatabaseToSharedFolder(Array, Array)\n#3 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(123): call_user_func_array(Array, Array)\n#4 \/usr\/share\/php\/openmediavault\/rpc\/rpc.inc(86): OMV\\Rpc\\ServiceAbstract->callMethod('dumpDatabaseToS...', Array, Array)\n#5 \/usr\/sbin\/omv-engined(536): OMV\\Rpc\\Rpc::call('MySql', 'dumpDatabaseToS...', Array, Array, 1)\n#6 {main}"}}`

**Comment by happyreacer** [comment]
@ryecoaaron  do you planed to adappt the scheduled backup option to mariadb?

**Comment by ryecoaaron** [comment]
The scheduled backup should work with mariadb.  It might not work if you upgraded from OMV 3 because the backup option is still trying to use root.  If you reset your password (omvadmin mysql user in OMV 4), it will recreate the password file that mysqldump uses.

**Comment by happyreacer** [comment]
@ryecoaaron Thanks a lot for this information! It works
